spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: stud-service
          uri: lb://STUD-SERVICE
          predicates:
            - Path=/student/**
        - id: fee-service
          uri: lb://FEE-SERVICE
          predicates:
            - Path=/dopayment/**
server:
  port: 8989
eureka:
  instance:
    hostname: myimage
  client:
    serviceUrl:
      defaultZone: http://myimage:8761/eureka/